### ISSUE TITLE
Bump dependency on google-cloud-storage '~> 0.21.0' if possible. Latest version is around '1.4.0'

### ISSUE THREAD

**Issue by johnmcconnell** [metaware/carrierwave-google-storage#12]
So going from `0.21.0` -> is 'supposed' to have a breaking change so we may want to be a little careful tackling this one.

**Comment by jasdeepsingh** [comment]
good point @johnmcconnell - I'll have to park this one for now as it requires some more thorough testing before releasing the change on rubygems. Will have to be a pre-release.
