### ISSUE TITLE
How to implement with CarrierWave Uploader

### ISSUE THREAD

**Issue by dessery85** [metaware/carrierwave-google-storage#2]
Hi

First of my apologies if im being stupid on this, but I am struggling to see how to integrate this into my application. I have previously been integrating with google storage via carrierwave and fog but I am getting performance issues so I thought I would try this instead.

I have gone through all the steps and have carrierwave configured to use the cloud settings but what do I need to do with my CarrierWave Uploader? Previously I was using :fog as the storage setting but obviously that is no longer the case. Do I need to use a particular value to get this to work? I have tried guessing a few options but with no joy.

Many thanks in advance

All the best

**Comment by jasdeepsingh** [comment]
@dessery85 thanks for your question. The storage engine name to use is:

```
class FileUploader < CarrierWave::Uploader::Base
   storage :gcloud
end
```

I should probably update the documentation with this info.
