### ISSUE TITLE
Good security practise to commit credentials to service accounts?

### ISSUE THREAD

**Issue by stabenfeldt** [metaware/carrierwave-google-storage#20]
Hi,

Is there a way to avoid adding service account credentials to the source?
Ref
```
CarrierWave.configure do |config|
  # [cut..]
  config.gcloud_credentials = {
    gcloud_keyfile: 'path-to-gcp-keyfile.json'
  }
end
```
How about using [Kubernetes secrets](https://kubernetes.io/docs/concepts/configuration/secret/) instead?

**Comment by jasdeepsingh** [comment]
I have not tried this, but one of my other gem called `underlock`: https://github.com/metaware/underlock might help with this:

```
require 'underlock'

# file.text.enc is an encrypted file encrypted using underlock gem
file = File.open('/path/to/your/secret/file.txt.enc')

CarrierWave.configure do |config|
  # [cut..]
  config.gcloud_credentials = {
    gcloud_keyfile: Underlock::EncryptedEntity.new(encrypted_file: file, key: key, iv: iv).decrypt
  }
end
```

As you can notice, you are free to use any encrypting/decrypting strategy not just underlock's, you can roll your own as well if you like. If you use underlock, you'll have to secure your private key, `key` and `iv` somehow as well (same way you secure your `RAILS_MASTER_KEY`)

I also suggest you look into these API docs if you want to use the inbuilt `RAILS_MASTER_KEY`

https://api.rubyonrails.org/classes/Rails/Application.html#method-i-encrypted
https://api.rubyonrails.org/classes/ActiveSupport/EncryptedConfiguration.html

Let me know if you require any further help on this. I'll try to respond with some relevant code samples.
