### ISSUE TITLE
Which role should the service account have?

### ISSUE THREAD

**Issue by stabenfeldt** [metaware/carrierwave-google-storage#21]
![screenshot 2018-08-10 09 59 37](https://user-images.githubusercontent.com/181272/43945948-16b3f1e8-9c84-11e8-9e34-5f454f44c590.png)

**Cloud Datastore User**, perhaps? :)
![screenshot 2018-08-10 10 01 03](https://user-images.githubusercontent.com/181272/43946056-646017be-9c84-11e8-83b8-960d1ab5fed9.png)

**Comment by jasdeepsingh** [comment]
It should be Storage Admin Role. 

![screen shot 2018-09-25 at 12 06 50 pm](https://user-images.githubusercontent.com/603900/46027310-86ee9480-c0bb-11e8-92da-dfcffa7d713e.png)

Please comment on this issue again if you have any further questions and I'll reopen.
