### ISSUE TITLE
Cannot find file tmp/...

### ISSUE THREAD

**Issue by airjoshb** [metaware/carrierwave-google-storage#26]
I am switching from AWS storage to Google and while setup is quite simple and seems to work (the files are uploaded to my bucket), I am getting an error for the tmp files created by carrierwave, "cannot find file uploads/tmp/...". I can also see files that are already referenced in the database without error.

The file is uploaded and the error seems to stem back from the google-cloud-storage gem.

```
CarrierWave.configure do |config|
  config.storage                             = :gcloud
  config.cache_storage                       = :gcloud
  config.gcloud_bucket                       = [my bucket]
  config.gcloud_bucket_is_public             = true
  config.gcloud_authenticated_url_expiration = 600

  config.gcloud_attributes = {
    expires: 600
  }
  
  config.gcloud_credentials = {
    gcloud_project: [my project],
    gcloud_keyfile: [my keyfile]
  }
end
```
and my uploader
```
class ImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  include Piet::CarrierWaveExtension

  storage :gcloud

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end
end
```

**Comment by jasdeepsingh** [comment]
This is the first time I'm hearing about an issue like this. I'd request you to follow up on this thread with the following information:

1. Is your `tmp/` directly writable from the ruby/rails process?
2. Do you have a proper stack trace that you can share about this error?

Thanks!

**Comment by otukutun** [comment]
@airjoshb @jasdeepsingh Would you please tell me any updates?

I got same error.  I tried to update this gem to be able to use Carrerwave 2.0 version. (REF: https://github.com/otukutun/carrierwave-google-storage/tree/feature/update-carrierwave) but I failed.

In 2.0, Carrerwave became that use same storages storage and cache_storage by default.  In this gem, when I use google-cloud-storage by cache storage, I got the error "cannot find file uploads/tmp/xxx-xxx-xxx/image1.png"

This is repository which happens the same error. REF: https://github.com/otukutun/carrierwave-google-storage/tree/feature/update-carrierwave

**Comment by jasdeepsingh** [comment]
A new version will be released shortly of this gem, please try that and report back if this issue persists. Closing for now.
