### ISSUE TITLE
Only depend on google-cloud-storage gem

### ISSUE THREAD

**Issue by JanStevens** [metaware/carrierwave-google-storage#3]
We are now including the complete google cloud gem with everything.

In light of killing dependencies could this gem only depend on the actual storage gem?
https://github.com/GoogleCloudPlatform/google-cloud-ruby#storage

```
gem install google-cloud-storage
```

**Comment by jasdeepsingh** [comment]
@JanStevens That's a good suggestion - I've opened up a PR for the same, will merge as soon as the CI is green. Thanks again.

**Comment by jasdeepsingh** [comment]
@JanStevens this has been fixed in 0.6.0. I suggest upgrading to this version for your projects. Thanks for your patience on this.
