### ISSUE TITLE
GcloudFile DelegationError

### ISSUE THREAD

**Issue by vanboom** [metaware/carrierwave-google-storage#31]
Thanks for a great gem. 

When remote files are not present, some GcloudFile methods that are delegated to the file fail...

```
Module::DelegationError: CarrierWave::Storage::GcloudFile#size delegated to file.size, but file is nil:
```
Suggest allowing nil in the delegation in gcloud_file.rb line 11

```ruby
delegate :content_disposition, :content_type, :size, to: :file, allow_nil: true
```
Would you suggest that we handle the exception in our application rather than allow nil on the delegation?   I am happy to offer a PR if you would accept the `allow_nil: true` option.

**Comment by jasdeepsingh** [comment]
This was merged as part of https://github.com/metaware/carrierwave-google-storage/pull/32 Closing.
