### ISSUE TITLE
Problem using hash version of keyfile

### ISSUE THREAD

**Issue by eLod** [metaware/carrierwave-google-storage#37]
`google-cloud-core` supports having the `keyfile` (`credentials`) passed as a hash (https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-core/lib/google/cloud.rb#L45).

There is a slight problem caused by this library and ruby, because how the object is created (https://github.com/metaware/carrierwave-google-storage/blob/master/lib/carrierwave/storage/gcloud.rb#L42), specifically when the second argument of the `::Google::Cloud.new` is a hash ruby tries to map it onto keyword arguments which causes an `ArgumentError: unknown keywords: type, project_id, private_key_id,...`. Explicitly adding a third argument to the `new` call (like an empty hash) solves the problem.

I can cook up a small PR to add an empty hash (or even support the 2 options `Google::Cloud.new` currently has, e.g. `retries` and `timeout`) if you agree with the above.

**Comment by jasdeepsingh** [comment]
@eLod Can you please try the latest version of this gem and see if it's still an issue with the latest release? 
If it is, I would welcome a PR.

Thanks!

**Comment by eLod** [comment]
yes, i can confirm with version 1.0.0 (carrierwave at 1.3.2) the error is present

**Comment by eLod** [comment]
i am happy to do the PR, do you have any specific recommendations? also do you want to add support for `retries` and `timeout` (and if yes do you want to add new configs to the uploader) or just an empty hash?
