### ISSUE TITLE
Options params is ignored on url method.

### ISSUE THREAD

**Issue by rodrigoulisses** [metaware/carrierwave-google-storage#41]
Hi people.
I'm trying set options params on `file.url(query: { "response-content-disposition": "attachment; filename=#{filename(output_file)}"})`  method, but it's not work.

Created a PR to fix this method #40

Tks

**Comment by BhartiN** [comment]
I am awaiting a fix for this. Do you know if there's a bummer here to get your PR merged except failing build?

**Comment by jasdeepsingh** [comment]
Fix has been merged into `master` Will be doing a release shortly with this fix. Stay tuned and thank you for your contribution!
