### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by drex333** [metaware/carrierwave-google-storage#43]
Github dependant bot is raising:
 Dependabot cannot update carrierwave to a non-vulnerable version
The latest possible version that can be installed is 1.2.3 because of the following conflicting dependency:

carrierwave-google-storage (0.9.0) requires carrierwave (~> 1.2.0)
The earliest fixed version is 1.3.2.

**Comment by jasdeepsingh** [comment]
Fix has been merged, I'll do a new release of the Gem tomorrow evening. 

See: https://github.com/metaware/carrierwave-google-storage/pull/42/files

**Comment by drex333** [comment]
Thank you! I will try then. So fast response, great!

**Comment by anitsirc** [comment]
@jasdeepsingh Where are you doing the releases? cannot see anything new under releases nor in rubygems  🤷🏻‍♀️

**Comment by jasdeepsingh** [comment]
Sorry - I’ve contracted and tested positive for Covid. I’m quarantining and recovering right now. 

Hopefully, when I’m fully recovered and back to work next week - I’ll do a release. 

Appreciate the patience.

**Comment by anitsirc** [comment]
Hope you have a speedy recovery 🙏

**Comment by jasdeepsingh** [comment]
Thank you for your contribution! A new release is coming up soon! Stay tuned.

**Comment by anitsirc** [comment]
@jasdeepsingh I still don't see a new version. Latest one seems to be 0.9.0 from 2018.

**Comment by jasdeepsingh** [comment]
@anitsirc For now you can point to this git tag on github: https://github.com/metaware/carrierwave-google-storage/tree/v1.0.0

I'm resolving my access with Rubygems support. Once it's resolved I'll publish the gem to Rubygems.
