### ISSUE TITLE
1.0 is missing on Rubygems.org

### ISSUE THREAD

**Issue by dlackty** [metaware/carrierwave-google-storage#46]
As titled, the latest version on Rubygems.org is still 0.9.0:
https://rubygems.org/gems/carrierwave-google-storage/

Maybe @jasdeepsingh forgot to publish it?

**Comment by anitsirc** [comment]
Seem they were having some issues in getting access to rubygems as discussed here https://github.com/metaware/carrierwave-google-storage/issues/43

@jasdeepsingh any updates?

**Comment by jasdeepsingh** [comment]
@anitsirc @dlackty 

1.0.0 is published to rubygems now: https://rubygems.org/gems/carrierwave-google-storage/versions/1.0.0
