### ISSUE TITLE
How to upload public and private files ?

### ISSUE THREAD

**Issue by webattitude** [metaware/carrierwave-google-storage#5]
I need to upload some files publicly, some other ones privately

**Comment by jasdeepsingh** [comment]
@webattitude you should make two buckets: one public and one private. Configure your public files to go in the public bucket and private files in the private bucket. Use `authenticated_url` method to render links to the private files.

PS: sorry for the delay on the reply.

**Comment by sureshprasanna70** [comment]
@jasdeepsingh How do I get an authenticated url?
I have an `user` model and an uploader named `pic` , accessing `user.pic.authenticated_url` returns undefined method
