### ISSUE TITLE
by_verifying_existance will not work if gcloud doesn't throw an exception on a not found file

### ISSUE THREAD

**Issue by johnmcconnell** [metaware/carrierwave-google-storage#8]
https://github.com/metaware/carrierwave-google-storage/blob/master/lib/carrierwave/storage/gcloud_file.rb#L26

**Comment by codegoalie** [comment]
Looks like new versions of the gcloud gem will not throw this error anymore: https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/bucket.rb#L562

**Comment by johnmcconnell** [comment]
So should we create an issue to bump the gcloud gem version?

**Comment by johnmcconnell** [comment]
I'll just go ahead and do that

**Comment by jasdeepsingh** [comment]
@codegoalie aww, they are eating up the exception silently. I'll start revising this bit.

**Comment by jasdeepsingh** [comment]
this gem has been updated to use a more recent version of `gcloud`, please update to `0.8.0`

**Comment by johnmcconnell** [comment]
Thanks!
