### ISSUE TITLE
Explore option to avoid expensive gcloud API calls when ActiveRecord resource loads

### ISSUE THREAD

**Issue by johnmcconnell** [metaware/carrierwave-google-storage#9]

**Comment by jasdeepsingh** [comment]
can you outline where these expensive calls are happening?

**Comment by johnmcconnell** [comment]
Yeah, it just hasn't been a priority, currently. When it comes up again in my stack, I'll be sure to update the issue.

**Comment by dko26** [comment]
PIggybacking off this issue to shed some light on what we're experiencing regarding the same thing:

I'm finding that whenever we issue a `find` call for an ActiveRecord resource that has an uploaded file, it's making 2 calls: one for retrieving the GCS bucket and another for the file itself. This is happening without calling the accessor for the resource, in our case: `avatar`. Additionally, for each version of the file, it issues another 2 calls. However, subsequent calls to the same resource no longer call GCS.

### Example
```
resource = Resource.find(1)    # issues 2 calls to GCS: bucket and file
resource.avatar                # doesn't issue any more calls to GCS
```

The PR https://github.com/metaware/carrierwave-google-storage/pull/14 fixes the calls to the file but I find that the initial call to the bucket remains.

### Example after PR
```
resource = Resource.find(1)    # issues 1 call to GCS: bucket
resource.avatar                # doesn't issue any more calls to GCS
```

**Comment by jasdeepsingh** [comment]
@dko26 @johnmcconnell please try version `0.8.0` and feel free to open this issue again if this is still an issue.
